version: 2

build:
  os: ubuntu-22.04
  tools:
    python: '3.11'
  jobs:
    post_checkout:
      - git fetch --unshallow || true

python:
  install:
    - requirements: requirements-doc.txt
    - requirements: requirements-dev.txt
    - requirements: requirements.txt
