ARG PYTHON_VERSION=3.7
FROM python:${PYTHON_VERSION}-slim as base
RUN apt-get update && apt-get install make --no-install-recommends

COPY docker/pip.conf /etc/pip.conf
RUN pip install -U pip --no-cache-dir

WORKDIR /app
COPY requirements.txt requirements-test.txt /app/
RUN pip install -r requirements.txt -r requirements-test.txt --no-cache-dir

ENV PYTHONPATH "/app:$PYTHONPATH"
ENV PATH /app:$PATH

COPY mlflow_client /app/mlflow_client
COPY integration-tests.sh coverage.sh wait-for-it.sh __init__.py /app/
COPY tests /app/tests

SHELL ["/bin/bash", "-c"]
CMD integration-tests.sh
