name: Dev release

on:
  push:
    branches-ignore:
      - dependabot/**
      - pre-commit-ci-update-config
  workflow_dispatch:

env:
  DEFAULT_PYTHON: '3.12'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  wait-code-analysis:
    name: Release package
    runs-on: ubuntu-latest
    if: github.repository == 'MobileTeleSystems/mlflow-rest-client'  # prevent running on forks

    environment:
      name: test-pypi
      url: https://test.pypi.org/p/mlflow-rest-client
    permissions:
      id-token: write # to auth in Test PyPI

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python ${{ env.DEFAULT_PYTHON }}
        id: python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}

      - name: Upgrade pip
        run: python -m pip install --upgrade pip setuptools wheel

      - name: Build package
        run: python setup.py sdist bdist_wheel

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
